---
name: Release
on: [ push ]
jobs:
  github-release:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: >
          jq -r ".version" "manifest.json" | grep "${{ github.ref_name }}"
      - run: >
          gh release create "${{ github.ref_name }}"
          --target "${{ github.sha }}"
          --generate-notes
          --verify-tag
          --draft
        env:
          GH_TOKEN: "${{ github.token }}"
...
